nuxtlabs/vue-telescope-analyzer

- README.md
- detectors/frameworks.json
- icons/framework/inertiajs.svg
Adds [Inertia.js](https://inertiajs.com) as a detectable framework
Adding a new detector for the Inertia.js framework, similar to `vuepress` it can be detectable by checking `__vue__.$inertia`
Inertia.js Vue Example : https://demo.inertiajs.com/login
> feat: add Inertia.js in frameworks

- README.md
- bin/vta.js
- package.json
- src/index.js
- src/utils.js
- yarn.lock
Remove aws chrome to use puppeteer dependency, this will allow us to have a better service for analyzing showcase online.
> feat!: remove chromium and use puppeteer

- README.md
- detectors/plugins.json
- icons/plugins/vee-validate.svg
This PR adds detection code for vee-validate `v2` and `v3`
> feat: add vee-validate to plugins

- README.md
Bad yarn install command for NPM part.
> fix: yarn install command

- icons/ui/vue-tailwind.svg
The vue-tailwind logo was recently updated for the one on this PR, (just changed the color)
> Update vue-tailwind logo

- detectors/plugins.json
Update the existing `Inertia.js` detector and detection for vue 3
Demo Link: https://breeze-inertia-vue3.vercel.app/
> chore: add Inertia.js detection for vue 3

- detectors/nuxt.modules.json
> feat: update @nuxtjs/dayjs module

- detectors/nuxt.modules.json
> Added DruxtJS detector.

- README.md
just small typos & consistency changes
> docs: small tweaks to readme

- detectors/plugins.json
> fix: correct typo in vuex detector

- detectors/uis.json
Adds new Vue 3 detector for @chakra-ui/vue 3
> feat(detector): update Vue 3 detector for chakra-ui/vue-next

- README.md
- detectors/plugins.json
> feat: add detector for `@vue/composition-api`

- detectors/nuxt.modules.json
In this merge request, I have added `nuxt-typo3` module to `nuxt.modules.json`. This is a headless solution for typo3 cms 
(https://github.com/TYPO3/typo3) based on nuxt. Examples of commercial usage nuxt-typo3:
https://www.macmillanenglish.com/
https://www.raben-group.com/
https://www.biofarm.pl/
https://www.kartamultisport.pl/
https://www.robomow.com/
Link to the repository on GitHub of this solution: 
https://github.com/TYPO3-Initiatives/nuxt-typo3
> feat: add nuxt-typo3

- detectors/nuxt.modules.json
> feat: add @nuxtjs/i18n module

- detectors/uis.json
- src/detectors.js
As discussed https://github.com/nuxtlabs/vue-telescope-analyzer/pull/29#issuecomment-1035128981, this PR allows to prioritize the scan of UI libraries rather than CSS framework; for example, Oruga or Vue Tailwind vs TailwindCSS.
> feat: ui detectors priority

- detectors/nuxt.modules.json
Additional option to detect Algolia module for Nuxt https://algolia.nuxtjs.org/
> feat: detect @nuxtjs/algolia

- detectors/uis.json
Fix typo on Vulk product : Culk - Vulk
> fix: typo on Vulk product

- detectors/nuxt.meta.json
- detectors/nuxt.modules.json
- Support isServerRendered for Nuxt 3
- Update supported modules detection
- Added Directus module (@Intevel)
- Added Supabase module (@larbish)
> feat: add more support for Nuxt 3

- README.md
- detectors/plugins.json
- icons/plugins/formkit.svg
Adds [FormKit](https://formkit.com/) as a detectable plugin. FormKit is the spiritual successor to [@braid/vue-formulate](https://vueformulate.com) for Vue 3. FormKit is a form building framework that simplifies form structure, generation, validation, theming, submission, error handling, and more.
Adds a detector for `@formkit/vue` by looping through all DOM nodes looking for any instances of `__vue_app__` that have a `$formkit` key in their `globalProperties`.
> feat: add FormKit detector

- src/utils.js
I removed node-fetch introduced in src/utils.js because it is not directly needed in the project, this dependency is useless, and it will cause the extension to crash when opening some websites.
Resolves: #98
> fix: remove unused dependency causing errors

- README.md
- detectors/uis.json
Replacing the old PrimeVue URL https://www.primefaces.org/primevue/showcase which is 404 now, to the proper current homepage https://primevue.org.
> chore: update PrimeVue urls
